# Site settings
title: Matt Bessey
email: bessey@gmail.com
description: Web Dev / Nerd / Californian Tourist
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bessey.io" # the base hostname & protocol for your site
twitter_username: mjhbessey
github_username:  bessey

# Build settings
markdown: kramdown

# Custom
permalink: /blog/:year/:month/:day/:title/

disqus_short_name: besseysblog
disqus_show_comment_count: false

google_analytics_tracking_id: UA-39945482-1
