# Site settings
title: Bessey's Blog
email: bessey@gmail.com
description: Technical blog of a full stack software engineer, working on all things web since 2013
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bessey.dev" # the base hostname & protocol for your site
twitter_username: mjhbessey
github_username:  bessey

# Build settings
markdown: kramdown

# Custom
permalink: /blog/:year/:month/:day/:title/

disqus_short_name: besseysblog
disqus_show_comment_count: false

# google_analytics_tracking_id: UA-39945482-1

excerpt_separator: <!-- more -->

highlighter: rouge

kramdown:
  syntax_highlighter: rouge
